application_api_version: v1beta1
properties:
  APP_INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME
  NAMESPACE:
    type: string
    default: kube-system
    x-google-marketplace:
      type: NAMESPACE
  IMAGE_ROBIN_OPERATOR:
    type: string
    default: $REGISTRY/robinoperator:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_ROBIN:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
  IMAGE_UBBAGENT:
    type: string
    default: $REGISTRY/ubbagent:1.0
    x-google-marketplace:
      type: IMAGE
  IMAGE_PROVISIONER:
    type: string
    default: $REGISTRY/csi-provisioner:v0.4.1_robin
    x-google-marketplace:
      type: IMAGE
  REPORTING_SECRET:
    type: string
    default: ""
    x-google-marketplace:
      type: REPORTING_SECRET
  SERVICE_ACCOUNT:
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed for the operator
      to create Robin CRD and resources
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          # TODO(barney-s): Reduce the permission set.
          rulesFromRoleName: cluster-admin
required:
- APP_INSTANCE_NAME
- IMAGE_ROBIN_OPERATOR
- IMAGE_ROBIN 
- IMAGE_PROVISIONER
- SERVICE_ACCOUNT
